### PR TITLE
MOD-UI: Filter out ports with specific designations

### PR DESCRIPTION
**Pull request by jwoillez**
Some MOD-UI ports with a designation are not meant to be modified. This is not handled properly by Zynthian and causes MOD-UI server crashes and Zynthian UI freezes.
For a description of the underlying issue see: https://github.com/moddevices/mod-ui/pull/110
I originally mentioned the issue there: https://discourse.zynthian.org/t/hi-all-bug-with-mod-ui/4843
Note that another user reported a similar issue there: https://discourse.zynthian.org/t/mod-ui-server-interference-with-zynthian-box-controller-knobs/4854

### CODE REVIEW

**Comment by jwoillez** [comment]
Note, this should fix #293.

**Comment by jwoillez** [comment]
@jofemodo About the refactor above, don't you have to remove the `not` in the `if` statement if you use `continue`?

**Comment by jofemodo** [comment]
Ups!! Done!! ;-)

**Comment by jofemodo** [comment]
OK! Merged, my friend.
Thanks for your contribution!
Don't doubt to make more if you feel the need ... jeje!

**Pull request merged**
