### PR TITLE
Pianoteq fixes

### PR DESCRIPTION
**Pull request by mheidt**
Changes and fixes for
#405 Add new Pianoteq instrument Petrof Mistral
Fix bug of missing presets
Sort bank_list
PEP8 formatting
#351 Pianoteq: reading prefs file for product value

### CODE REVIEW

**Comment by jofemodo** [comment]
Nice @mheidt!

It seems good but had no time to test tonight. I will test it tomorrow. Next time, please, split the "code styling" in a different PR. Code review is easier.

Thanks a lot!

**Comment by riban-bw** [comment]
I don't see Petrof Mistral in my list of demo instruments. I am running Pianoteq Stage 7.3.0.

**Comment by riban-bw** [comment]
I installed Pianoteq Stage 7.4.2 and now see Petrof Mistrel in the list of demo instruments and it seems to work as expected. I am happy with the PR.

**Comment by jofemodo** [comment]
OK It's merged now. Thanks a lot, @mheidt !

**Comment by mheidt** [comment]
@jofemodo 
Is it possible to cherry pick this to stable as well?
Missing the new instrument und default presets.
And I don't expect testing to be usable in the near future.

**Pull request merged**
