### PR TITLE
Feature/cuia recording

### PR DESCRIPTION
**Pull request by riban-bw**
Adds MIDI and audio record and stop functions to CUIA.

### CODE REVIEW

**Comment by riban-bw** [comment]
May I suggest that you use the PR mechanism within GitHub to discuss submissions, e.g. query why things are coded in a particular way, recommend or request changes like coding styles, etc? Also when merging it may be advantageous to squash the PR to avoid muddying the version history of the main branch. (There are often irrelevant commits during development of a patch.)

**Comment by jofemodo** [comment]
Hi @riban-bw!

I suggest to avoid the creation of the new start/stop functions in the "zynthian_gui" class. 
The logging line is redundant:

`logging.info("Start audio recorder")`

because the start_recording/stop_recording functions already has a logging line. So better call directly from the "callable_ui_action" function to:

`self.screens['audio_recorder'].start_recording()`

`self.screens['audio_recorder'].stop_recording()`

Thanks!

**Comment by jofemodo** [comment]
OK! I will use the "squash merge" ... 

Thanks for the advice! ;-)

**Comment by riban-bw** [comment]
Good call. I added the extra functions before I found where / how to call the screen functions and added the logging to trace flow whilst debugging. Both removed now and much neater.

**Pull request merged**
