### PR TITLE
#180 MP3 player

### PR DESCRIPTION
**Pull request by mheidt**
Easy addon that doesn't hurt anyone...

### CODE REVIEW

**Comment by jofemodo** [comment]
Why not including ogg too?

**Comment by mheidt** [comment]
Because I didn't needed it and I don't know what that player is capable of.

**Comment by mheidt** [comment]
The only disadvantage I see is, that you see the converted ogg files as well, so that they are shown twice...as wav and ogg.
I can checkin the enhanced if statement.

**Comment by jofemodo** [comment]
OK! Don't add ogg by now ...

**Pull request merged**
