### PR TITLE
Adds audio level monitoring

### PR DESCRIPTION
**Pull request by riban-bw**
Adds stereo peak audio monitoring.

- Status bar switchable between CPU / audio monitoring by setting ZYNTHIAN_UI_SHOW_CPU (True / False)
- Displays 2 horizontal bars indicating audio peak level
- Spans range -50dBFS to -10dBFS (green), -10dBFS to -3dBFS (yellow), -3dBFS to 0dBFS (red)
- Logarithmic range
- Damped decay

Not yet implemented:
- ~~Auto connect (must currently connect instruments using audio routing)~~ [Done]
- ~~Scale legend, e.g. vertical graduation marks~~ [Won't do]
- ~~Peak level hold, e.g. highest value showing as vertical line for a second~~ [Done]
- ~~No CPU / RAM bench marking yet performed~~ [Done]

Known issues:
- Low resolution screen (160 pixel wide) does not show red zone)

### CODE REVIEW

**Comment by riban-bw** [comment]
I have benchmarked against master and cannot detect increase in cpu usage when metering is added.
I can't figure out how autoconnect works so haven't been able to automatically feed the audio monitor. Please help!

**Comment by riban-bw** [comment]
I tried adding graduation marks but it didn't look good. I added default routing of layer to level meters and peak hold indicators. The small issue with the red not showing on low resolution screens can be a follow-on action. I think this looks quite good now. Please review and feedback.

Areas I think might need attentions:
- Naming - jackpeak might not be the best name, maybe levelmeter or similar. The library does show peaks in a JACK input!
- There is a lot of code in the display. It looks clumsy to me but I am a C/C++ programmer so don't know whether Python is supposed to look like this!
- Is the range okay? I chose -50dB because it looks about right. Fluidsynth is rather noisy with noise floor sitting about -157dB (okay - not that noisy but it is worse than others). I don't think we need to see this noise on our meter (external monitoring could pick that up). 50dB below fsd seems a reasonable range though it could possibly be a little smaller.
- Add switch to toggle between CPU / audio level - maybe in webconf.

**Comment by riban-bw** [comment]
Issue: Inserting an effect in a layer does not remove the routing of the engine from the meter. Need to figure this out (probably mod to autoroute?).

**Comment by jofemodo** [comment]
Hi @riban-bw!

As seems to have a good git/github knowldge, i would like to comment with you about the best practices and workflow for improving zynthian development.

For instance, what is the best way of testing this pull request?

1. Clone locally and test your forked repo before merging with master
2. Merge your PR in a "testing" branch.
3. Other

Thanks a lot!

**Comment by jofemodo** [comment]
Ahhh! I have invited you to be a "member" of zynthian team, so you can create branches and push to all but master ;-)

**Comment by jofemodo** [comment]
I created a specific branch "gh93-levelmeter" and merge the pull request on it for testing.

**Comment by jofemodo** [comment]
Hi @riban-bw !
It works really nice. Congratulations!!
A few adjustments for perfect integration:

+ Regarding the jack client name: jackpeak is OK for me. It's the original codename and clear enough for something quite techy that only developers needs to know ;-)

+ Regarding jackpeak itself: It seems quite simple and eficient. Anyway, perhaps some functions are not used nor needed: connect, disconnect & disconnectAll
I've tested without this functions and it works perfectly too. Less is more ;-)

+ Regarding the audio routing, it's better you do nothing in "zyngine/zynthian_layer.py" and implement the "magic" in the autoconnector. Please, remove this change and i will add jackpeak to the autoconnector.

**Comment by jofemodo** [comment]
OK! Already commited some changes on the branch gh93-levelmeter ... 0;-)

**Pull request merged**
