### PR TITLE
Don't use controller as button in some cases

### PR DESCRIPTION
**Pull request by steveb**
This change reduces the situations where a controller will trigger a
button push:
- If onscreen buttons are enabled, never use controllers as buttons
- If the controller value has been changed during the push event,
  don't trigger a button on release

This makes it practical to use a touchscreen-only zynthian to change
the controller values without triggering an undesired button press.

This fixes issue #401

### CODE REVIEW

**Comment by jofemodo** [comment]
Hi @steveb !

For your next contribution, as you have write access on this repository, i think it's better you create your development branch on it. In such a way it's more easy to test changes on zynthian.

**Comment by jofemodo** [comment]
After this change, controller areas don't work as "touch button". It seems your second change is too tight and it should be relaxed a little bit.

**Comment by jofemodo** [comment]
In fact, your second change doesn't work at all, at less on the ZynScreen display, so i must reject this change. I will accept the first one: "If onscreen buttons are enabled, never use controllers as buttons"

Regards,

**Comment by steveb** [comment]
> Hi @steveb !
> 
> For your next contribution, as you have write access on this repository, i think it's better you create your development branch on it. In such a way it's more easy to test changes on zynthian.

will do

**Comment by steveb** [comment]
> In fact, your second change doesn't work at all, at less on the ZynScreen display, so i must reject this change. I will accept the first one: "If onscreen buttons are enabled, never use controllers as buttons"

OK, I'll take out the canvas_motion_set_value mechanism and restore canvas_motion_count and motion_rate

**Comment by jofemodo** [comment]
I've already done it and it's already merged on testing.

Thanks!

**Pull request merged**
